import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import MusicWidget from "@/components/MusicWidget";
import MobileBlock from "@/components/MobileBlock";
import MobileRedirect from "@/components/MobileRedirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased bg-black`}
      >
  {/* Mobile redirect/enforcement (client-side) */}
  <MobileRedirect />
  {/* Mobile block overlay (client-side) */}
  <MobileBlock />
  {children}
  {/* Music widget: client-only persistent audio player */}
  <MusicWidget />
      </body>
    </html>
  );
}
